name: build-wheels
on:
  push: { tags: ["v*"] }
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: python -m pip install -U pip cibuildwheel build
      - name: System deps
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libgsl0-dev
      - name: System deps (macOS)
        if: runner.os == 'macOS'
        run: brew update && brew install gsl
      - name: Build wheels
        env:
          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"
          CIBW_SKIP: "pp* -musllinux_"
          CIBW_ARCHS_MACOS: "x86_64 arm64"
        run: python -m cibuildwheel --output-dir wheelhouse
      - name: Build sdist
        run: python -m build --sdist
      - name: Publish
        if: startsWith(github.ref, 'refs/tags/')
        uses: pypa/gh-action-pypi-publish@v1.10.1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
